apiVersion : apps/v1
kind: Deployment
metadata:
  name: pranjalsc 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pranjalsc
  template:
    metadata:
      labels:
        app: pranjalsc 
    spec:
      containers:
        - name: pranjalsc 
          image: kbcontregpp.azurecr.io/pranjalsc
          ports:
          - containerPort: 80